wandb_version: 1

K:
  desc: null
  value:
    value: 6
_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.12
batch_size:
  desc: null
  value:
    value: 64
eps:
  desc: null
  value: 1.0
knn:
  desc: null
  value: 16
learning_rate:
  desc: null
  value:
    value: 0.005
nsym:
  desc: null
  value: 1
pooling:
  desc: null
  value:
    value: max
weight_decay:
  desc: null
  value:
    value: 0.0005
xi:
  desc: null
  value: 0.05
